### ISSUE TITLE
Specify a `artifactId` for this project

### ISSUE THREAD

**Issue by souenzzo** [portkey-cloud/cfn-yaml#1]
Without one clear `id`, we can have "double import" issues.

If `projectA` use `portkey-cloud/cfn-yaml {:git/url ... :sha v1}`
and `projectB` use `cfn-yaml {:git/url ... :sha v2}`

the final `classpath` will contain both `v1` and `v2`.

It's usually something like
`portkey-cloud/cfn-yaml`
or 
`your.domain/cfn-yaml`

https://clojure.org/reference/deps_and_cli#_dependencies

**Comment by viesti** [comment]
Good point! Maybe this could be raised in say Clojurians Slack #tools-deps channel? I don't there is a way to force an artifact id on a git deps library since it can be chosen by the consumer of the library.

**Comment by souenzzo** [comment]
From clojurians #tools-deps slack:

https://clojurians-log.clojureverse.org/tools-deps/2020-02-19

Dominic
- I generally strongly recommend a id in the readme

Alex Miller 
- Seems like a good practice 
- it kind of is with the advice of `github-yourname/time-lib`

https://www.clojure.org/guides/deps_and_cli#_using_git_libraries

**Comment by viesti** [comment]
Nice, thanks for the effort in communication! :) I updated the readme a bit, adding a suggestion of the artifact id to use: https://github.com/portkey-cloud/cfn-yaml/commit/9483b99f0a858fa3c77b98b32f8234d975064e0a
